

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(blank=True, max_length=3)),
                ('icao_code', models.CharField(blank=True, max_length=4)),
                ('max_passengers', models.PositiveIntegerField()),
                ('first_class_capacity', models.PositiveIntegerField(default=0)),
                ('business_class_capacity', models.PositiveIntegerField(default=0)),
                ('premium_economy_capacity', models.PositiveIntegerField(default=0)),
                ('economy_capacity', models.PositiveIntegerField(default=0)),
                ('range_km', models.PositiveIntegerField(help_text='Range in kilometers')),
                ('cruise_speed_kmh', models.PositiveIntegerField(help_text='Cruise speed in km/h')),
                ('ceiling_ft', models.PositiveIntegerField(blank=True, help_text='Service ceiling in feet', null=True)),
                ('max_takeoff_weight', models.PositiveIntegerField(blank=True, help_text='MTOW in kg', null=True)),
                ('maintenance_check_frequency', models.PositiveIntegerField(blank=True, help_text='Number of flight hours between maintenance checks', null=True)),
                ('turn_around_time_minutes', models.PositiveIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='IATA 3-letter code', max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, help_text='ICAO 4-letter code', max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('elevation', models.IntegerField(blank=True, help_text='Elevation in feet', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hub', models.BooleanField(default=False, help_text='Whether this is a hub airport for the airline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TravelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('seat_pitch', models.PositiveIntegerField(blank=True, help_text='Seat pitch in inches', null=True)),
                ('seat_width', models.PositiveIntegerField(blank=True, help_text='Seat width in inches', null=True)),
                ('seat_recline', models.PositiveIntegerField(blank=True, help_text='Seat recline in degrees', null=True)),
                ('has_priority_boarding', models.BooleanField(default=False)),
                ('has_lounge_access', models.BooleanField(default=False)),
                ('has_fast_track', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_power_outlets', models.BooleanField(default=False)),
                ('has_premium_meals', models.BooleanField(default=False)),
                ('has_extra_baggage', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier applied to base fare price', max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Class',
                'verbose_name_plural': 'Travel Classes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fleet_number', models.CharField(max_length=10, unique=True)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('standby', 'Standby'), ('storage', 'In Storage'), ('retired', 'Retired')], default='active', max_length=20)),
                ('flight_hours', models.PositiveIntegerField(default=0)),
                ('cycles', models.PositiveIntegerField(default=0, help_text='Number of takeoff-landing cycles')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('first_class_seats', models.PositiveIntegerField(default=0)),
                ('business_class_seats', models.PositiveIntegerField(default=0)),
                ('premium_economy_seats', models.PositiveIntegerField(default=0)),
                ('economy_seats', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='flights.aircrafttype')),
                ('base_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_aircraft', to='flights.airport')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['fleet_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('days_of_operation', models.CharField(help_text="Days of operation, e.g., '1234567' for all days, '1' for Monday only", max_length=7)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_schedules', to='flights.aircrafttype')),
            ],
            options={
                'verbose_name': 'Flight Schedule',
                'verbose_name_plural': 'Flight Schedules',
                'ordering': ['flight_number', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('arrived', 'Arrived'), ('diverted', 'Diverted'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_departure', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('gate_departure', models.CharField(blank=True, max_length=10)),
                ('gate_arrival', models.CharField(blank=True, max_length=10)),
                ('terminal_departure', models.CharField(blank=True, max_length=10)),
                ('terminal_arrival', models.CharField(blank=True, max_length=10)),
                ('cruising_altitude', models.PositiveIntegerField(blank=True, help_text='Altitude in feet', null=True)),
                ('distance_flown', models.PositiveIntegerField(blank=True, help_text='Actual distance flown in km', null=True)),
                ('departure_delay_minutes', models.IntegerField(default=0)),
                ('arrival_delay_minutes', models.IntegerField(default=0)),
                ('delay_reason', models.TextField(blank=True)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('is_codeshare', models.BooleanField(default=False)),
                ('codeshare_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.aircraft')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='flights.airport')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.flightschedule')),
                ('available_travel_classes', models.ManyToManyField(blank=True, related_name='flights', to='flights.travelclass')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['scheduled_departure'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('distance_km', models.PositiveIntegerField(help_text='Distance in kilometers')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Scheduled duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='flights.airport')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['origin__code', 'destination__code'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flights.route'),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='available_travel_classes',
            field=models.ManyToManyField(blank=True, related_name='flight_schedules', to='flights.travelclass'),
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('first_officer', 'First Officer'), ('purser', 'Purser'), ('cabin_crew', 'Cabin Crew'), ('relief_pilot', 'Relief Pilot')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_assignments', to='crew.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Flight Crew',
                'verbose_name_plural': 'Flight Crews',
                'ordering': ['flight', 'role'],
                'unique_together': {('flight', 'crew_member')},
            },
        ),
        migrations.CreateModel(
            name='FlightSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Sequence number of this sector')),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_air', 'In Air'), ('landed', 'Landed'), ('arrived', 'Arrived'), ('diverted', 'Diverted'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('gate_departure', models.CharField(blank=True, max_length=10)),
                ('gate_arrival', models.CharField(blank=True, max_length=10)),
                ('terminal_departure', models.CharField(blank=True, max_length=10)),
                ('terminal_arrival', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_arrivals', to='flights.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='flights.flight')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_departures', to='flights.airport')),
            ],
            options={
                'verbose_name': 'Flight Sector',
                'verbose_name_plural': 'Flight Sectors',
                'ordering': ['flight', 'sequence'],
                'unique_together': {('flight', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='flightschedule',
            unique_together={('flight_number', 'effective_from')},
        ),
    ]
